"""Allowed experiment provenance labels."""

ALLOWED_PROVENANCE_LABELS = {
    "LOCAL_REIMPLEMENTATION",
    "OFFICIAL_CHECKPOINT_REPRODUCTION",
    "OFFICIAL_CHECKPOINT_BASELINE",
    "OFFICIAL_CHECKPOINT",
    "PUBLISHED_PRECOMPUTED_FEATURE_EVALUATION",
    "INSUFFICIENT_RELEASED_IMPLEMENTATION",
}
